version : "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongoapp2  
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend2
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      - SREE=Mr.SreeCharan
volumes:
  mongodb_data:
networks : 
  my_network:
    driver: bridge